pm2 start main.js --no-autorestart --name onFoQ4ko74y -- onFoQ4ko74y quarterly
pm2 start main.js --no-autorestart --name RtEYsASU7PG -- RtEYsASU7PG monthly
pm2 start main.js --no-autorestart --name ic1BSWhGOso -- ic1BSWhGOso monthly
pm2 start main.js --no-autorestart --name nGkMm2VBT4G -- nGkMm2VBT4G monthly
pm2 start main.js --no-autorestart --name VDhwrW9DiC1 -- VDhwrW9DiC1 monthly
pm2 start main.js --no-autorestart --name quMWqLxzcfO -- quMWqLxzcfO monthly
pm2 start main.js --no-autorestart --name dFRD2A5fdvn -- dFRD2A5fdvn quarterly
pm2 start main.js --no-autorestart --name DFMoIONIalm -- DFMoIONIalm quarterly
pm2 start main.js --no-autorestart --name EBqVAQRmiPm -- EBqVAQRmiPm monthly